repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.3.0'
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: setup.cfg
  - repo: https://github.com/psf/black
    rev: '22.10.0'
    hooks:
      - id: black
        args:
          - --safe
          - --quiet
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/codespell-project/codespell
    rev: 'v2.2.1'
    hooks:
      - id: codespell
        args:
          - --skip="./.*,*.csv,*.json"
          - --quiet-level=2
        exclude_types: [csv, json]
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://gitlab.com/pycqa/flake8
    rev: '5.0.4'
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-docstrings==1.6.0
          - pydocstyle==6.1.1
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/PyCQA/pylint
    rev: 'v2.15.3'
    hooks:
      - id: pylint
        additional_dependencies:
          - pytest~=6.2.4
          - voluptuous>=0.12.1
          - aiohttp>=3.7.4
          - python-didl-lite~=1.3.2
          - defusedxml>=0.6.0
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/PyCQA/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args:
          - --profile=black
        files: ^(async_upnp_client|tests)/.+\.py$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.982'
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        additional_dependencies:
          - aiohttp>=3.7.4
          - pytest~=6.2.4
        files: ^(async_upnp_client|tests)/.+\.py$
